### ISSUE TITLE
Unity VisionOS support

### ISSUE THREAD

**Issue by yosun** [deepgram/UnityDeepgramDemo#1]
Hi! Does this work for Unity VisionOS?

**Comment by yosun** [comment]
It does!  2022.3.21

**Comment by nikolawhallon** [comment]
Hey that's awesome, I was gonna say I have no way to test really :(

**Comment by yosun** [comment]
hey! actually that might have been a false positive (possibly iOS compatibility build for visionOS, not visionOS, as i was very exhausted yesterday) - i can't seem to get the connection to sustain today (immediately closes) on the hackathon network or hotspot. 

culprit is whether the nativesockets package works for visionos (or just the existing platforms) 

```
NativeWebSocket.<Connect>d__27:MoveNext()
nw_socket_initialize_socket [C1:2] setsockopt SO_NECP_CLIENTUUID failed [22: Invalid argument]
nw_socket_copy_info [C1:2] getsockopt TCP_INFO failed [102: Operation not supported on socket]
nw_socket_copy_info getsockopt TCP_INFO failed [102: Operation not supported on socket]

```
